apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: konga
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: y8QXY6AL6JLH9Fx6
